app/urls.py
from django.urls import path
from app.views import *

app_name = 'Virat'

urlpatterns=[
    path('RCB/',RCB,name='RCB')
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name= 'Msd'

urlpatterns = [
    path('csk/',csk,name='csk')
]

mutileapp_urlnavigation/urls.py
from django.contrib import admin
from django.urls import path,include
import app,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app2/',include('app2.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.

def RCB(request):
    return render(request,'RCB.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def csk(request):
    return render(request,'csk.html')

templates/RCB.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is website for RCB fans</h1>
        <button><a href="{% url 'Msd:csk' %}">CLick</a>
        </button>
    </center>
</body>
</html>

templates/csk.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><h1>THis page is for csk fans</h1>
    <button>
        <a href="{% url 'Virat:RCB' %}">click</a>
    </button>
    </center>
</body>
</html>